version: '3.4'

services:
  meterssender:
    image: ${DOCKER_REGISTRY-}meterssender
    networks:
      - db
    build:
      context: .
      dockerfile: MetersSender/Dockerfile
   
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    networks:
      - db
    volumes:
      - db_volume:/data/postgres
      - db_volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=1234567890Qwerty
      - POSTGRES_USER=postgres
      - POSTGRES_DB=meters_db

volumes:
  db_volume:

networks:
  db:
    driver: bridge
